package Model;

// default package
// Generated 16/07/2014 08:36:51 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Opinion generated by hbm2java
 */
public class Opinion implements java.io.Serializable {

	private String opinion;
	private Opinion opinion_1;
	private Usuario usuario;
	private Noticia noticia;
	private String contenido;
	private Date fecha;
	private Boolean estado;
	private Set<Opinion> opinions = new HashSet<Opinion>(0);

	public Opinion() {
	}

	public Opinion(String opinion, Noticia noticia) {
		this.opinion = opinion;
		this.noticia = noticia;
	}

	public Opinion(String opinion, Opinion opinion_1, Usuario usuario,
			Noticia noticia, String contenido, Date fecha, Boolean estado,
			Set<Opinion> opinions) {
		this.opinion = opinion;
		this.opinion_1 = opinion_1;
		this.usuario = usuario;
		this.noticia = noticia;
		this.contenido = contenido;
		this.fecha = fecha;
		this.estado = estado;
		this.opinions = opinions;
	}

	public String getOpinion() {
		return this.opinion;
	}

	public void setOpinion(String opinion) {
		this.opinion = opinion;
	}

	public Opinion getOpinion_1() {
		return this.opinion_1;
	}

	public void setOpinion_1(Opinion opinion_1) {
		this.opinion_1 = opinion_1;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Noticia getNoticia() {
		return this.noticia;
	}

	public void setNoticia(Noticia noticia) {
		this.noticia = noticia;
	}

	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public Set<Opinion> getOpinions() {
		return this.opinions;
	}

	public void setOpinions(Set<Opinion> opinions) {
		this.opinions = opinions;
	}

}
