// default package
// Generated 16/07/2014 08:36:51 AM by Hibernate Tools 3.4.0.CR1
package Model;
import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil implements java.io.Serializable {

	private String perfil;
	private String descripcion;
	private Boolean estado;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Perfil() {
	}

	public Perfil(String perfil) {
		this.perfil = perfil;
	}

	public Perfil(String perfil, String descripcion, Boolean estado,
			Set<Usuario> usuarios) {
		this.perfil = perfil;
		this.descripcion = descripcion;
		this.estado = estado;
		this.usuarios = usuarios;
	}

	public String getPerfil() {
		return this.perfil;
	}

	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
