// default package
// Generated 16/07/2014 08:36:51 AM by Hibernate Tools 3.4.0.CR1
package Model;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private String usuario;
	private Perfil perfil;
	private String nombres;
	private String dni;
	private String correo;
	private Boolean estado;
	private String password;
	private Set<Opinion> opinions = new HashSet<Opinion>(0);
	private Set<Noticia> noticias = new HashSet<Noticia>(0);

	public Usuario() {
	}

	public Usuario(String usuario) {
		this.usuario = usuario;
	}

	public Usuario(String usuario, Perfil perfil, String nombres, String dni,
			String correo, Boolean estado, String password,
			Set<Opinion> opinions, Set<Noticia> noticias) {
		this.usuario = usuario;
		this.perfil = perfil;
		this.nombres = nombres;
		this.dni = dni;
		this.correo = correo;
		this.estado = estado;
		this.password = password;
		this.opinions = opinions;
		this.noticias = noticias;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Opinion> getOpinions() {
		return this.opinions;
	}

	public void setOpinions(Set<Opinion> opinions) {
		this.opinions = opinions;
	}

	public Set<Noticia> getNoticias() {
		return this.noticias;
	}

	public void setNoticias(Set<Noticia> noticias) {
		this.noticias = noticias;
	}

}
